<?php

namespace App\Logging;

class GlobalEventName {
    const PROCESS_STARTUP_FAILED = "PROCESS_STARTUP_FAILED";
    const USE_CASE_EXECUTION_FAILED = "USE_CASE_EXECUTION_FAILED";
    const USE_CASE_VALIDATION_FAILED = "USE_CASE_VALIDATION_FAILED";
    const SERVICE_REQUEST_FAILED = "SERVICE_REQUEST_FAILED";
    const DATABASE_REQUEST_FAILED = "DATABASE_REQUEST_FAILED";
    const SLOW_HTTP_REQUEST = "SLOW_HTTP_REQUEST";
    const APPLICATION_EVENT = "APPLICATION_EVENT";
}